module.exports = {
  content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // PsyOasis Design System (Landing page palette)
        primary: "#002768",
        "on-primary": "#ffffff",
        "primary-container": "#003b95",
        "on-primary-container": "#8cabff",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001847",
        "on-primary-fixed-variant": "#0e419b",
        secondary: "#006d31",
        "on-secondary": "#ffffff",
        "secondary-container": "#7afc9a",
        "on-secondary-container": "#007435",
        "secondary-fixed": "#7afc9a",
        "secondary-fixed-dim": "#5ddf81",
        "on-secondary-fixed": "#00210a",
        "on-secondary-fixed-variant": "#005324",
        tertiary: "#531600",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#782501",
        "on-tertiary-container": "#ff8f67",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed": "#380c00",
        "on-tertiary-fixed-variant": "#7f2a05",
        surface: "#f9f9fc",
        "surface-bright": "#f9f9fc",
        "surface-dim": "#dadadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f6",
        "surface-container": "#eeeef0",
        "surface-container-high": "#e8e8ea",
        "surface-container-highest": "#e2e2e5",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#434652",
        "inverse-surface": "#2f3133",
        "inverse-on-surface": "#f0f0f3",
        "inverse-primary": "#b2c5ff",
        outline: "#747783",
        "outline-variant": "#c4c6d4",
        "surface-tint": "#315ab4",
        "surface-variant": "#e2e2e5",
        background: "#f9f9fc",
        "on-background": "#1a1c1e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        secretOasis: {
          background: '#f9f9fc',
          text: '#1a1c1e',
          secondary: '#006d31',
          accent: '#315ab4',
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "stack-sm": "8px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        caption: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
